manifest:
  remotes:
    - name: NCKiser
      url-base: https://github.com/NCKiser
  projects:
    - name: zmk
      remote: NCKiser
      revision: main
      import: app/west.yml
  self:
    path: config
